version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: php:8.1-fpm-bullseye
    container_name: php_fpm
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
